spring:
  datasource:
    #    url: jdbc:mysql://120.55.160.101:3306/good_source?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://192.168.1.10:3306/good_source?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    #    username: root
    #    password: root
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #      stat-view-servlet:
      #          allow: 120.55.160.101:3306
      filter:
        wall:
          config:
            multi-statement-allow: true
  redis:
    # host: 192.168.207.128
    host: 192.168.1.10
    port: 6379
    # password: admin
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 100
        min-idle: 10
    database: 0
    timeout: 10s
  jackson:
    default-property-inclusion: ALWAYS
  http:
    encoding:
      charset: UTF-8
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
server:
  port: 8082
  #port: 8080
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  mapper-locations: classpath:mappers/*.xml

rsa:
  key:
    #       pubKeyFile: C:\auth_key\id_key_rsa.pub
    #       priKeyFile: C:\auth_key\id_key_rsa
    pubKeyFile: E:\yuechuang\auth_key\id_key_rsa.pub
    priKeyFile: E:\yuechuang\auth_key\id_key_rsa
logging:
  level:
    cn.zhuchuangsoft.footstone.mappers: error



